version: "3"

services:
    app:
        image: recommendation-service
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            ./.env
        ports:
           - "13003:3003"
        depends_on:
            - db
    db:
        image: mongo
        command: mongod --quiet --logpath /dev/null 
        ports:
            - "27017:27017"