definitions:
  controller.HealthResponse:
    properties:
      creation_date:
        type: string
      description:
        type: string
      last_response:
        type: string
    type: object
  controller.InterestsRule:
    properties:
      enabled:
        type: boolean
    required:
    - enabled
    type: object
  controller.ProximityRule:
    properties:
      enabled:
        type: boolean
      radius:
        type: integer
    required:
    - enabled
    - radius
    type: object
info:
  contact: {}
  description: Recommendation microservice for FiuFit's backend.
  title: Recommendation Microservice API
  version: "1.0"
paths:
  /:
    get:
      description: Returns a 200 code and JSON with a message.
      responses:
        "200":
          description: OK
      summary: Check the service's status.
  /health:
    get:
      description: Returns a 200 code and JSON with the date the service started running
        and a description.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.HealthResponse'
      summary: Get the service's health status.
  /rules/interests:
    get:
      description: Get the current settings of the interests rule.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.InterestsRule'
        "500":
          description: Internal Server Error
      summary: Get the current settings of the interests rule.
      tags:
      - Interests Rule
    patch:
      consumes:
      - application/json
      description: Update the interests rule' status for recommended trainings.
      parameters:
      - description: Interests rule changes
        in: body
        name: rule
        required: true
        schema:
          $ref: '#/definitions/controller.InterestsRule'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update the interests rule' status for recommended trainings.
      tags:
      - Interests Rule
  /rules/proximity:
    get:
      description: Get the current settings of the proximity rule.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ProximityRule'
        "500":
          description: Internal Server Error
      summary: Get the current settings of the proximity rule.
      tags:
      - Proximity Rule
    patch:
      consumes:
      - application/json
      description: Update the maximum radius for recommended trainings.
      parameters:
      - description: Proximity rule changes
        in: body
        name: rule
        required: true
        schema:
          $ref: '#/definitions/controller.ProximityRule'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update the maximum radius for recommended trainings.
      tags:
      - Proximity Rule
swagger: "2.0"
