name: Linter and Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run format
        run: go fmt ./...

      - name: Run linter
        run: go vet ./...

      - name: Run tests
        run: go test ./__test__
